name: ML CI/CD (Docker)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pytest -q

  docker-train:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ml-ci-cd-demo .
      - name: Run Docker container (training)
        run: docker run --rm -v ${{ github.workspace }}/artifacts:/app/artifacts ml-ci-cd-demo
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ml-artifacts
          path: artifacts/
